# Generated by Django 3.1.7 on 2021-06-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210601_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
