# Generated by Django 3.1.7 on 2021-07-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='temp',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
