version: '3.9'
 
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    command: >
      sh -c "ls -lrt &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_HOST=${POSTGRES_HOST}
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_HOST=${POSTGRES_HOST}
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "djangoproject", "-U", "mshashank"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
  redis:
    image: redis
    
